item { 
	name:'Red-Nothing-Nothing-Nothing'
	id:1
}
item { 
	name:'Nothing-Red-Nothing-Nothing'
	id:2
}
item { 
	name:'Nothing-Nothing-Nothing-Nothing'
	id:3
}
item { 
	name:'Red-Red-Nothing-Nothing'
	id:4
}
